"""academy v2 schema

Revision ID: 20260820_0001
Revises:
Create Date: 2026-08-20 23:07:02.802818
"""

import sqlalchemy as sa
from alembic import op

revision = "20260820_0001"
down_revision = None
branch_labels = None
depends_on = None

FTS_UPGRADE_STATEMENTS = (
    """CREATE VIRTUAL TABLE notes_fts USING fts5(
        title, body, content='notes', content_rowid='id'
    )""",
    """CREATE TRIGGER notes_ai AFTER INSERT ON notes BEGIN
        INSERT INTO notes_fts(rowid, title, body) VALUES (new.id, new.title, new.body);
    END""",
    """CREATE TRIGGER notes_ad AFTER DELETE ON notes BEGIN
        INSERT INTO notes_fts(notes_fts, rowid, title, body)
        VALUES ('delete', old.id, old.title, old.body);
    END""",
    """CREATE TRIGGER notes_au AFTER UPDATE ON notes BEGIN
        INSERT INTO notes_fts(notes_fts, rowid, title, body)
        VALUES ('delete', old.id, old.title, old.body);
        INSERT INTO notes_fts(rowid, title, body) VALUES (new.id, new.title, new.body);
    END""",
    """CREATE VIRTUAL TABLE source_blocks_fts USING fts5(
        text, content='source_blocks', content_rowid='id'
    )""",
    """CREATE TRIGGER source_blocks_ai AFTER INSERT ON source_blocks BEGIN
        INSERT INTO source_blocks_fts(rowid, text) VALUES (new.id, new.text);
    END""",
    """CREATE TRIGGER source_blocks_ad AFTER DELETE ON source_blocks BEGIN
        INSERT INTO source_blocks_fts(source_blocks_fts, rowid, text)
        VALUES ('delete', old.id, old.text);
    END""",
    """CREATE TRIGGER source_blocks_au AFTER UPDATE ON source_blocks BEGIN
        INSERT INTO source_blocks_fts(source_blocks_fts, rowid, text)
        VALUES ('delete', old.id, old.text);
        INSERT INTO source_blocks_fts(rowid, text) VALUES (new.id, new.text);
    END""",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_devices_role"), "devices", ["role"], unique=False)
    op.create_table(
        "drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("covered_block_ids", sa.JSON(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("validation_report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learning_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lesson_ids", sa.JSON(), nullable=False),
        sa.Column("current_lesson_id", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "linux_hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("runner_username", sa.String(length=80), nullable=False),
        sa.Column("encrypted_private_key", sa.Text(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("encrypted_runner_private_key", sa.Text(), nullable=False),
        sa.Column("runner_public_key", sa.Text(), nullable=False),
        sa.Column("pending_host_key", sa.Text(), nullable=True),
        sa.Column("host_key", sa.Text(), nullable=True),
        sa.Column("host_key_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_preflight_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pairing_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("requested_role", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_pairing_codes_expires_at"), "pairing_codes", ["expires_at"], unique=False
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=120), nullable=False),
        sa.Column("lesson_id", sa.String(length=120), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_items_due_at"), "review_items", ["due_at"], unique=False)
    op.create_index(op.f("ix_review_items_skill_id"), "review_items", ["skill_id"], unique=False)
    op.create_table(
        "skill_states",
        sa.Column("skill_id", sa.String(length=120), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("successful_fingerprints", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_table(
        "studio_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("extractor", sa.String(length=80), nullable=False),
        sa.Column("immutable_ok", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_name"),
    )
    op.create_index(op.f("ix_studio_sources_sha256"), "studio_sources", ["sha256"], unique=False)
    op.create_table(
        "target_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("container_reference", sa.String(length=128), nullable=False),
        sa.Column("container_port", sa.Integer(), nullable=False),
        sa.Column("image_digest", sa.String(length=255), nullable=False),
        sa.Column("host_endpoint", sa.String(length=500), nullable=False),
        sa.Column("health_check", sa.JSON(), nullable=False),
        sa.Column("reset_policy", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("allowed_curriculum_tags", sa.JSON(), nullable=False),
        sa.Column("exposure_warnings", sa.JSON(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "container_reference", "container_port", name="uq_target_container_port"
        ),
    )
    op.create_index(
        op.f("ix_target_profiles_fingerprint"), "target_profiles", ["fingerprint"], unique=False
    )
    op.create_table(
        "lab_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.String(length=120), nullable=False),
        sa.Column("skill_id", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("target_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prediction", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("tutor_feedback_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tutor_question", sa.Text(), nullable=True),
        sa.Column("tutor_explanation", sa.Text(), nullable=True),
        sa.Column("correction", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("terminal_inputs", sa.JSON(), nullable=False),
        sa.Column("terminal_input_offsets", sa.JSON(), nullable=False),
        sa.Column("grader_status", sa.String(length=30), nullable=True),
        sa.Column("grader_report", sa.JSON(), nullable=False),
        sa.Column("relay_port", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["learning_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lab_runs_lesson_id"), "lab_runs", ["lesson_id"], unique=False)
    op.create_index(op.f("ix_lab_runs_session_id"), "lab_runs", ["session_id"], unique=False)
    op.create_index(op.f("ix_lab_runs_skill_id"), "lab_runs", ["skill_id"], unique=False)
    op.create_index(
        "uq_lab_runs_one_active",
        "lab_runs",
        ["status"],
        unique=True,
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_lab_runs_target_fingerprint"), "lab_runs", ["target_fingerprint"], unique=False
    )
    op.create_table(
        "source_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("locator", sa.String(length=120), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["studio_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "ordinal", name="uq_source_block"),
    )
    op.create_index(
        op.f("ix_source_blocks_source_id"), "source_blocks", ["source_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=120), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=False),
        sa.Column("target_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("grader_decision", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lab_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "skill_id", name="uq_evidence_run_skill"),
    )
    op.create_index(op.f("ix_evidence_run_id"), "evidence", ["run_id"], unique=False)
    op.create_index(op.f("ix_evidence_skill_id"), "evidence", ["skill_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("lesson_id", sa.String(length=120), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("source_v1_id", sa.Integer(), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lab_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    for statement in FTS_UPGRADE_STATEMENTS:
        op.execute(sa.text(statement))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP TRIGGER IF EXISTS source_blocks_au"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS source_blocks_ad"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS source_blocks_ai"))
    op.execute(sa.text("DROP TABLE IF EXISTS source_blocks_fts"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS notes_au"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS notes_ad"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS notes_ai"))
    op.execute(sa.text("DROP TABLE IF EXISTS notes_fts"))
    op.drop_table("notes")
    op.drop_index(op.f("ix_evidence_skill_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_run_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_source_blocks_source_id"), table_name="source_blocks")
    op.drop_table("source_blocks")
    op.drop_index(op.f("ix_lab_runs_target_fingerprint"), table_name="lab_runs")
    op.drop_index(op.f("ix_lab_runs_skill_id"), table_name="lab_runs")
    op.drop_index(op.f("ix_lab_runs_session_id"), table_name="lab_runs")
    op.drop_index(op.f("ix_lab_runs_lesson_id"), table_name="lab_runs")
    op.drop_index("uq_lab_runs_one_active", table_name="lab_runs")
    op.drop_table("lab_runs")
    op.drop_index(op.f("ix_target_profiles_fingerprint"), table_name="target_profiles")
    op.drop_table("target_profiles")
    op.drop_index(op.f("ix_studio_sources_sha256"), table_name="studio_sources")
    op.drop_table("studio_sources")
    op.drop_table("skill_states")
    op.drop_index(op.f("ix_review_items_skill_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_due_at"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_pairing_codes_expires_at"), table_name="pairing_codes")
    op.drop_table("pairing_codes")
    op.drop_table("linux_hosts")
    op.drop_table("learning_sessions")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_devices_role"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
